sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: '336014169'
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  wechat:
    appid: wx68bd2781f451b3e4
    secret: acbd333f06a8908be367825f54ed1ab0
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t9XUgc5W7oLLhxkALM5
    access-key-secret: FTHjJp84uL7XAIvO7kvGFwIMS474w2
    bucket-name: da-shuaige
